#!/usr/bin/env bash
# Generates the local cluster's keys, once, into a gitignored file.
#
#   scripts/dev-secrets.sh            # generate if absent, otherwise say nothing
#   scripts/dev-secrets.sh --force    # generate again, replacing what is there
#   scripts/dev-secrets.sh --print    # show what the seeded admin signs in with
#
# The file is read by k8s/overlays/local through a secretGenerator, so
# `skaffold dev` and `kubectl apply -k` both pick it up with no wrapper. It is
# generated rather than committed because a key in the repository is a key
# every clone shares and every scanner reports -- and these keys are not
# interchangeable between tiers, so the one thing that must not happen is each
# tier inventing its own.
set -euo pipefail

cd "$(dirname "$0")/.."
# shellcheck source=lib/keys.sh
source scripts/lib/keys.sh

file=k8s/overlays/local/dev-secrets.env
force=false
print=false
for arg in "$@"; do
  case "$arg" in
    --force) force=true ;;
    --print) print=true ;;
    *)
      echo "unknown argument: $arg" >&2
      exit 2
      ;;
  esac
done

if [[ "$print" == true ]]; then
  if [[ ! -f "$file" ]]; then
    echo "no $file yet: run scripts/dev-secrets.sh" >&2
    exit 1
  fi
  # Only the two anybody types. The keys are in the file for whoever needs
  # them and printing them here would mean scrolling past them every time.
  grep -E '^OUTTURN_DEV_ADMIN_(EMAIL|PASSWORD)=' "$file"
  exit 0
fi

if [[ -f "$file" && "$force" != true ]]; then
  # Quiet on the common path: this runs before every `skaffold dev`, and a
  # line saying nothing happened is a line nobody reads.
  exit 0
fi

if [[ -f "$file" ]]; then
  echo "replacing $file; sessions signed with the old key stop working" >&2
fi

secret=$(outturn_token_secret)
public=$(outturn_public_key_of "$secret")
runtime=$(outturn_runtime_key)
password=$(outturn_dev_password)

umask 077
cat >"$file" <<EOF
# Generated by scripts/dev-secrets.sh. Not committed, and not shared with any
# other machine: these are this clone's local keys.
#
# Delete this file and run the script again to rotate them. Everything signed
# with the old key -- browser sessions, mostly -- stops being accepted.

# The API signs with this; the gateway and runtime verify with its public
# half. They must belong to each other, so change them together or not at all.
OUTTURN_TOKEN_SECRET=$secret
OUTTURN_TOKEN_PUBLIC_KEY=$public

# What the runtime presents to take work. Means "the runtime tier", nothing more.
OUTTURN_RUNTIME_KEY=$runtime

# Who OUTTURN_DEV_SEED creates on an empty database, for signing in locally.
OUTTURN_DEV_ADMIN_EMAIL=admin@outturn.local
OUTTURN_DEV_ADMIN_PASSWORD=$password
EOF

echo "wrote $file" >&2
echo "  sign in with admin@outturn.local / $password" >&2
