apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - minio.yaml
  - postgres.yaml
  - mockllm.yaml
  - hollowbrook.yaml
  - networkpolicy.yaml
